### ISSUE TITLE
Initialization configuration

### ISSUE THREAD

**Issue by ingted** [NTDLS/NTDLS.Katzebase.Server#64]
Hi, how do we configure password for admin account? through appsettings.json?
Or what's the default password for admin?

**Comment by ingted** [comment]
After I change the code in Engine project from

```
replace all KbInsensitiveDictionary<string?>
```

to

```
static public List<PreparedQuery> PrepareBatch(string queryText, KbInsensitiveDictionary<KbConstant?>? userParameters = null)
```

The error becomes to 

```
[07:56:43 ERR] Failed to acquire schema for process id 1. Schema [master:account] does not exist.
[07:56:43 ERR] Failed to execute document select for process id 1. Schema [master:account] does not exist.
[07:56:43 ERR] Failed to execute query for process id 1. Schema [master:account] does not exist.
[07:56:43 ERR] Failed to start session for session id a1b0a0d2-c0d4-472a-93a9-0017a53b966d. Schema [master:account] does not exist.
```

**Comment by ingted** [comment]
Hi I finally gather all the repo into one place and align all the KbInsensitiveDictionary<KbConstant?>? type and use the demo server & mgmtUI to create master:acount and add admin account.

Finally I could connect successfully through mgmtUI built from source...

Katzebase is so amazing!!!

For reference...
https://github.com/ingted/Katzebase

**Comment by NTDLS** [comment]
Yep, the accounts are stored in the schema master:acount. The username is text, and the password is a sha256 of the desired password. This works with a clean install, but unfortunately I have not really worried about backward compatibility when using a new version of the engine with an "older" database. That is in the pipeline, but this thing is fundamentally changing too frequently while in its alpha stage.

**Comment by NTDLS** [comment]
This needs to be set when the database is first created.

**Comment by NTDLS** [comment]
I added the creation of the default account when the root schema is created. Should probably allow the user to specify this somehow, but we'll get there later.
