### ISSUE TITLE
Using FinalValue when insert (?)

### ISSUE THREAD

**Issue by ingted** [NTDLS/NTDLS.Katzebase.Server#65]
Hi I found that in

```
internal KbActionResponse ExecuteInsert(SessionState session, PreparedQuery preparedQuery)
```

The line 

```
fieldValue = functionConstantParameter.RawValue;
```

Would lead insert operation with redundant quotes(or maybe I am wrong because not really understand the query execution process)

But when I change it to 
```
fieldValue = functionConstantParameter.FinalValue;
```
Then I could use it without quote issue so far...

**Comment by NTDLS** [comment]
You are correct, but this SmartValue class has been removed in an active branch which is intended to be committed next week.
We have actually replaced the query parser, condition parser, added windowing functionality, and greatly optimized index usage.

We've also simplified the query process a good bit.

...check back in ~10 days.

**Comment by NTDLS** [comment]
Also, this new branch has a new set of query APIs called fetch, which work much like dapper for SQL Server and also support parameters.

```
class Person {
    public string FirstName { get; set; }
    public string LastName { get; set; }
}

var people = client.Query.Fetch<Person>(
	"SELECT FirstName, LastName FROM People WHERE Id = @Id" , new { Id = 10 });

foreach (var person in people)
{
	Console.WriteLine($"[{person .FirstName}],[{person .LastName}]");
}
```
