### ISSUE TITLE
Query result added to warnings in.... accident?

### ISSUE THREAD

**Issue by ingted** [NTDLS/NTDLS.Katzebase.Server#67]
Using commit 80e24e7cbda49ae8292f53fd1a4644d55d970498

And added codes to file:
```
NTDLS.Katzebase.Server\NTDLS.Katzebase.Engine\Interactions\APIHandlers\SessionAPIHandlers.cs
```

codes:
```
                    preLogin = _core.Sessions.CreateSession(Guid.NewGuid(), param.Username, param.ClientName);


                    _core.Query.ExecuteNonQuery(preLogin, "create schema master");

                    _core.Transactions.Commit(preLogin);

                    _core.Query.ExecuteNonQuery(preLogin, "create schema master:account");
                    _core.Transactions.Commit(preLogin);

                    using var transactionReference = _core.Transactions.Acquire(preLogin);

                    _core.Query.ExecuteNonQuery(preLogin, "insert into master:account (\r\nUsername = 'admin', PasswordHash = 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'\r\n)");
                    _core.Transactions.Commit(preLogin);
```

And then when in the end of build the filtered query result, rows are added to warnings:

```
foreach (var field in instance.Operation.Query.Conditions.AllFields.Where(o => o.Prefix == schemaKey).Distinct())
{
    if (schemaResultRow.AuxiliaryFields.ContainsKey(field.Key) == false)
    {
        if (documentContent.TryGetValue(field.Field, out fstring? documentValue) == false)
        {
            instance.Operation.Transaction.AddWarning(KbTransactionWarning.ConditionFieldNotFound,
                $"'{field.Key}' will be treated as null.");
        }
        schemaResultRow.AuxiliaryFields.Add(field.Key, documentValue);
    }
}
```

![image](https://github.com/user-attachments/assets/a98b9264-7314-472d-95be-08bfcf24dcc6)

Please ignore the unmatched id/pwd, I use the unmatched one to show which are input from mgmt UI and others are data stored in the page.

Even I used correct id/pwd, I would got

```
throw new Exception("Invalid username or password.");
```

in SessionAPIHandlers.cs

**Comment by ingted** [comment]
![image](https://github.com/user-attachments/assets/58f54f9f-d00b-43c8-84f9-539f77f46384)

**Comment by NTDLS** [comment]
I hate to do this to you, but I just pushed over 200 changes in ~120 commits. These changes have been in the pipeline for a while, and the changes are big and likely break some stuff. Unfortunately, these changes needed to be made, but on the bright-site cleanup 99% of the unattainability issues of the engine and parser.

The good news is, I think the server is now in a state that you can make meaningful changes.

Take a look!

# Changes
* Rewrote tokenizer.
* Rewrote entire query parser.
  * Parsers are now separated into separate static classes for each query type.
  * Parsers are now reusable, allowing for the condition parser, field parser and the like to be reused inside other query parser types.
 * Functions are now fully recursive and are parsed in select fields, group by, order by, insert, update, select, where clause and join clauses.
* Update statements now allow for joins.
* Delete statements now allow for joins.
* Introduced "insert select from" statements.
* Temporarily removed support for procedures, they will need to be reimplemented.
* Major changes to the way that indexes are selected and used. Multiple values for a single index are now handled in one index lookup operation.
* Condition parser rewrite is now more robust and understandable.
* Introduction of new dapper like queries using classes as return objects.
* Introduction of parameterized queries prevents sql-injection attacks.
* Scaler and aggregate function parser rewrite allowing for reusability in various parts of queries.
* Added inline query string concatenation.
* Added query field type detection for inline math and string aggregation to coexist without "casting" which would be found in other RDBMSs.
* Added windowing functionality with TOP and OFFSET.

# Remaining to-do:
  * Reimplement "SELECT INTO".
  * Reimplement stored procedures.
  * More robust parser validation.

**Comment by ingted** [comment]
Hi Josh,

Thank you for taking the time to make all these changes; it seems like a significant step for the long-term development of the system! I really love Katzebase and I could see the big potential of it! ^0^

I wish our collaboration goes smoothly and is enjoyable for both of us, so if my previous questions or feedback caused any inconvenience, I sincerely apologize. If you feel that I should have done more research or gained a better understanding of the code before asking questions, please feel free to let me know directly—I’m always open to improving.

Let me use the latest code now to see how to go for next step!! YOU ARE REALLY AWESOME!!!

**Comment by NTDLS** [comment]
Your understanding of this database system is quite impressive! I’m actually surprised anyone has dug this deeply into the code. What time zone are you in?

I do not find your questions or comments inconvenient, I look forward to them!!

**Comment by NTDLS** [comment]
Also, I pushed some more changes fixing a lot of what I broke with the previous giant update.

The remaining thing to reimplement is: stored procedures. I’m also going to look into reducing lock contention on inserts. I’m currently importing the StackOverflow.com database into Katzebase for testing. I’ll post the resulting database but it’s going to be be BIG! 😁
